language: java

jdk:
  - oraclejdk8

sudo:
  false

install:
  ./gradlew assemble

script:
  ./gradlew clean check

after_script:
  ./gradlew -Pversioneye.api_key=$VERSIONEYE_API_KEY versioneye-update